server:
  port: 8080
  servlet:
    context-path: /api

spring:
  mvc:
    format:
      date-time: yyyy-MM-dd'T'HH:mm:ss
  application:
    name: message_routing
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mq_messages}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
ibm:
  mq:
    host: ${IBM_MQ_HOST:localhost}
    port: ${IBM_MQ_PORT:1414}
    queue-manager: ${IBM_MQ_QUEUE_MANAGER:QM1}
    channel: ${IBM_MQ_CHANNEL:DEV.APP.SVRCONN}
    queue: ${IBM_MQ_QUEUE:DEV.QUEUE.1}
    user: ${IBM_MQ_USER:app}
    password: ${IBM_MQ_PASSWORD:app_password}
